// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfcfmcosgilkadzblvvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmY2ZtY29zZ2lsa2FkemJsdnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxOTc1MzAsImV4cCI6MjA1ODc3MzUzMH0.4Ysdw0KsOFPk5XU6AZYnbLNXfJ2EdP3vrCdP3kgbDUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);